name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake
        
      - name: Setup Qt 6.9.0
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.9.0'
          host: 'linux'

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -- -j

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
